
# .tbls.yml

# 接続先として、データベースの種類(`mysql`)、ユーザ名(`dbuser`)、パスワード(`dbpass`)、ホスト名(`localhost`)、ポート(`3306`)、データベース名(`dbname`)を以下のように記載します
# dsn: mysql://dbuser:dbpass@localhost:3306/dbname
dsn: mysql://root:secret@localhost:3306/homestead

# ドキュメントのディレクトリを指定します
docPath: doc/schema


    # environment:
    #   MYSQL_DATABASE: homestead
    #   MYSQL_USER: homestead
    #   MYSQL_ROOT_PASSWORD: secret
    #   SERVICE_TAGS: dev
    #   SERVICE_NAME: mysql
